#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
  ifeq ($(GNUSTEP_MAKEFILES),)
    $(warning )
    $(warning Unable to obtain GNUSTEP_MAKEFILES setting from gnustep-config!)
    $(warning Perhaps gnustep-make is not properly installed,)
    $(warning so gnustep-config is not in your PATH.)
    $(warning )
    $(warning Your PATH is currently $(PATH))
    $(warning )
  endif
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 1.13
PACKAGE_NAME = TimeTracker
APP_NAME = TimeTracker
TimeTracker_APPLICATION_ICON = 


#
# Resource files
#
TimeTracker_RESOURCE_FILES = \
    English.lproj/MainMenu.xib \
    English.lproj/TaskEditor.xib \
    Graphics/*.png \
    TimeTrackerInfo.plist

#
# Header files
#
TimeTracker_HEADER_FILES = \



#
# Objective-C Class files
#
TimeTracker_OBJC_FILES = \


#
# Other sources
#
TimeTracker_OBJC_FILES += \
main.m 

#
# Makefiles
#
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
